### ISSUE TITLE
[Bug]: post-install.sh does not detect the 'json' extension on PHP 8.1.29

### ISSUE THREAD

**Issue by wslyhbb** [DataDog/dd-trace-php#2704]
### Bug report

post-install.sh does not detect the `json` extension on Alpine with PHP 8.1.29. As shown in the php -m listing below, the json extension is installed but post-install.sh cannot detect it:

```
PHP 8.1.29 (cli) (built: Jun  6 2024 17:00:13) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.29, Copyright (c) Zend Technologies
### Installing Datadog PHP tracing extension (ddtrace)
###
### Logging /usr/bin/php -i to a file
###
lib/apk/exec/datadog-php-tracer-0.99.1.post-install: line 46: -d: command not found
lib/apk/exec/datadog-php-tracer-0.99.1.post-install: line 46: -d: command not found
lib/apk/exec/datadog-php-tracer-0.99.1.post-install: line 46: -d: command not found
lib/apk/exec/datadog-php-tracer-0.99.1.post-install: line 46: -d: command not found
lib/apk/exec/datadog-php-tracer-0.99.1.post-install: line 46: -d: command not found
Checking for extension: json
lib/apk/exec/datadog-php-tracer-0.99.1.post-install: line 46: -d: command not found
Error: PHP extension 'json' was not found.
ERROR: datadog-php-tracer-0.86.2.post-install: script exited with error 1
```

Issue is with detecting PHP version (lines 25-38):
```
# We attempt in this order the following binary names:
#    1. php
#    2. php8 (some alpine versions install php 8.x from main repo to this binary)
#    3. php7 (some alpine versions install php 7.x from main repo to this binary)
#    4. php5 (some alpine versions install php 5.x from main repo to this binary)
if [ -z "$DD_TRACE_PHP_BIN" ]; then
    DD_TRACE_PHP_BIN=$(command -v php || true)
fi
if [ -z "$DD_TRACE_PHP_BIN" ]; then
    DD_TRACE_PHP_BIN=$(command -v php8 || true)
fi
if [ -z "$DD_TRACE_PHP_BIN" ]; then
    DD_TRACE_PHP_BIN=$(command -v php7 || true)
fi
```

I think DD_TRACE_PHP_BIN is not getting set because /usr/bin/php8 does not exist. The folder is /usr/bin/php81 and the code is not looking for that.
Symbolically linking php81 to php8 prior to installing the tracer fixes the issue:
ln -s /usr/bin/php81 /usr/bin/php8

### PHP version

PHP 8.1.29 (cli) (built: Jun  6 2024 17:00:13) (NTS) Copyright (c) The PHP Group Zend Engine v4.1.29, Copyright (c) Zend Technologies

### Tracer or profiler version

datadog-php-tracer_0.99.1_x86_64.apk

### Installed extensions

[PHP Modules]
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
json
ldap
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
Phar
readline
Reflection
session
SimpleXML
sodium
SPL
standard
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]

### Output of `phpinfo()`

NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.19.1
PRETTY_NAME="Alpine Linux v3.19"

### Upgrading from

PHP 8.1.27

**Comment by iamluc** [comment]
Thank you for your detailed report @wslyhbb!
The next release should fix this issue.

**Comment by josephwynn-sc** [comment]
Hi team! Do you have an estimated date for the next release?

**Comment by iamluc** [comment]
HIi @wslyhbb 
We've just released version 1.2.0, which fixes this issue.

**Comment by iamluc** [comment]
> Hi team! Do you have an estimated date for the next release?

@josephwynn-sc Done in version 1.2.0. Sorry for the delay.

**Comment by josephwynn-sc** [comment]
I am still getting this error on Heroku with PHP 8.2.22. It seems like the installer is trying to run `php-fpm` as if it were a PHP binary:

```
       Installed required source files to '/tmp/build_176a8f4c/opt/dd-library/1.2.0'
       Installing to binary: php (/tmp/build_176a8f4c/.heroku/php/bin/php)
       Installing extension to /app/.heroku/php/lib/php/extensions/no-debug-non-zts-20220829
       Copied '/tmp/dd-install/dd-library-php/trace/ext/20220829/ddtrace.so' to '/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20220829/ddtrace.so'
       Copied '/tmp/dd-install/dd-library-php/profiling/ext/20220829/datadog-profiling.so' to '/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20220829/datadog-profiling.so'
       Copied '/tmp/dd-install/dd-library-php/appsec/ext/20220829/ddappsec.so' to '/app/.heroku/php/lib/php/extensions/no-debug-non-zts-20220829/ddappsec.so'
       Created INI file '/app/.heroku/php/etc/php/conf.d/98-ddtrace.ini'
       Installation to 'php (/tmp/build_176a8f4c/.heroku/php/bin/php)' was successful
       Installing to binary: php-fpm (/tmp/build_176a8f4c/.heroku/php/sbin/php-fpm)
       Killed
       PHP Deprecated:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in /tmp/codon/tmp/buildpacks/766a320daf1a9dc2c1b3c389285af80d17945984/datadog-setup.php on line 1106
       ERROR: Required PHP extension 'json' not found.
```

The "explode(): Passing null to parameter #2" makes me think
